@Calendar_HostAddress = http://localhost:5231

POST {{Calendar_HostAddress}}/calendarEvent/
Content-Type: application/json

{
    "name": "Test",
    "startDateTime": "2024-09-04T10:00:00",
    "endDateTime": "2024-09-04T18:00:00"
}
